# Generated by Django 3.1.4 on 2021-01-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('developpeur', 'developpeur'), ('designer', 'designer'), ('invité', 'invité')], default='invité', max_length=300),
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitulé', models.CharField(max_length=300)),
                ('période', models.DateField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitulé', models.CharField(max_length=300)),
                ('établissement', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('date_de_début', models.DateField()),
                ('date_de_fin', models.DateField()),
                ('diplômes_obtenus', models.CharField(max_length=300)),
                ('domaine', models.CharField(max_length=300)),
                ('langages_de_programmation', models.CharField(max_length=300)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profile')),
            ],
        ),
    ]
