# Generated by Django 3.1.4 on 2021-01-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210107_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='projets',
            name='lien',
            field=models.URLField(null=True),
        ),
    ]
