# Generated by Django 3.1.4 on 2021-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_projets_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('developpeur', 'developpeur'), ('designer', 'designer'), ('invité', 'invité')], max_length=300),
        ),
    ]
