# Generated by Django 3.1.4 on 2021-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210113_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('developpeur web', 'developpeur web'), ('developpeur mobile', 'developpeur mobile'), ('designer', 'designer'), ('invité', 'invité')], max_length=300),
        ),
    ]
