# Generated by Django 3.1.4 on 2021-01-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210113_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('developpeurWeb', 'developpeurWeb'), ('developpeurMobile', 'developpeurMobile'), ('designer', 'designer'), ('invité', 'invité')], max_length=300),
        ),
    ]
